<?php
/**
 * @file
 * Contains \Drupal\rsvplist\Form\RSVPSettingsForm
 */

namespace Drupal\rsvplist\Form;

use Drupal\Core\Form\ConfigFormBase;
use Symfony\Component\HttpFoundation\Request;
use Drupal\Core\Form\FormStateInterface;

/**
 * Class RSVPSettingsForm
 * @package Drupal\rsvplist\Form
 */
class RSVPSettingsForm extends ConfigFormBase
{
  /**
   * {@inheritDoc}
   */
  public function getFormID()
  {
    return 'rsvplist_admin_settings';
  }

  /**
   * {@inheritDoc}
   */
  protected function getEditableConfigNames()
  {
    return [
      'rsvplist.settings'
    ];
  }

  /**
   * @param array $form
   * @param FormStateInterface $form_state
   * @param Request|null $request
   * @return array
   */
  public function buildForm(array $form, FormStateInterface $form_state, Request $request = null)
  {
    $types = node_type_get_names();
    $config = $this->config('rsvplist.settings');
    $form['rsvplist_types'] = [
      '#type' => 'checkboxes',
      '#title' => $this->t('The content types to enable RSVP collection for'),
      '#default_value' => $config->get('allowed_types'),
      '#options' => $types,
      '#description' => $this->t('On the specified node types, an RSVP option will be available and can be enabled while that nod is being edited'),
    ];
    $form['array_filter'] = [
      'type' => 'value',
      '#value' => true
    ];
    return parent::buildForm($form, $form_state);
  }

  /**
   * @param array $form
   * @param FormStateInterface $form_state
   */
  public function submitForm(array &$form, FormStateInterface $form_state)
  {
    $allowed_types = array_filter($form_state->getValue('rsvplist_types'));
    sort($allowed_types);
    $this->config('rsvplist.settings')
      ->set('allowed_types', $allowed_types)
      ->save();
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }
}
